<?php

namespace Eteacher\InvictaAdmin\Tests\Feature;

use Eteacher\InvictaAdmin\Admin\Models\Group;
use Eteacher\InvictaAdmin\Admin\Models\Resources\Group as GroupResource;
use Eteacher\InvictaAdmin\Admin\Models\Resources\User as UserResource;
use Eteacher\InvictaAdmin\Admin\Resources\ResourceRegistrar;
use Eteacher\InvictaAdmin\Tests\Models\User;
use Eteacher\InvictaAdmin\Tests\TestCase;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\App;

class PermissionsTest extends TestCase
{
    protected $user;

    protected $group;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $resources = [GroupResource::class, UserResource::class];

        foreach ($resources as $resourceClass) {
            $resource = App::make($resourceClass);

            ResourceRegistrar::put($resource->handle(), $resource);
        }

        $this->user = User::factory()->create();
    }

    public function createGroupWithAbilities($abilities = null)
    {
        $this->group = new Group();
        $this->group->name = 'test';
        $this->group->title = 'Test';
        $this->group->is_super = $abilities ? 1 : 0;
        $this->group->save();

        if ($abilities) {
            $permisssions = Arr::map($abilities, function ($value) {
                return ['ability' => $value];
            });
            $this->group->permissions()->createMany($permisssions);
        }
    }

    public function test_permissions_can_be_edit()
    {
        $this->createGroupWithAbilities();

        $this->user->groups()->sync($this->group->id);
        dd($this->user->groups());

//
//        $response = $this
//             ->actingAs($this->user, config('invicta.auth.guard'))
//             ->get(route('invicta.resource', ['resource' => 'students']));
//        $response->dd();
    }
}
