<?php

namespace Elijahworkz\InvictaAdmin\Tests\Feature;

use Elijahworkz\InvictaAdmin\Admin\Resources\ResourceRegistrar;
use Elijahworkz\InvictaAdmin\Tests\Models\Invicta\Resources\Student;
use Elijahworkz\InvictaAdmin\Tests\TestCase;
use Illuminate\Support\Facades\App;
use Inertia\Testing\AssertableInertia as Assert;

class ResourceTest extends TestCase
{
    protected $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $resources = [Student::class];

        foreach ($resources as $resourceClass) {
            $resource = App::make($resourceClass);

            ResourceRegistrar::put($resource->handle(), $resource);
        }

        $this->user = $this->getUser(true);
    }

    public function test_resource_index()
    {
        $this->markTestSkipped();
        $response = $this
            ->withoutExceptionHandling()
            ->actingAs($this->user, config('invicta.auth.guard'))
            ->get(route('invicta.home'))
            ->assertInertia(fn (Assert $page) => $page
                ->component('Home')
                ->missing('email'));
    }
}
